os: linux

language: go

go:
    - 1.14.x

services:
    - docker

before_install:
    - docker pull postgres
    - docker run --name mypostgresdb -e POSTGRES_PASSWORD=postgres -d -p 5432:5432 postgres